name: Release Cocoapod

on:
 push:
  branches:
    - master

jobs:
  check_if_release_is_needed:
    runs-on: macos-latest
    if: "contains(github.event.head_commit.message, '[make release]')"
    steps:
    - run: echo "${{ github.event.head_commit.message }}"

  publish:
    needs: check_if_release_is_needed
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.CI_TOKEN }}

    - name: Get Current Framework Version
      run: echo ::set-env name=RELEASE_NAME::$(./Scripts/get_version.sh)

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@latest
      env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
      with:
          tag_name: ${{ env.RELEASE_NAME }}
          release_name: Release ver. ${{ env.RELEASE_NAME }}
          body: Release ver. ${{ env.RELEASE_NAME }}
          draft: false
          prerelease: false
          
    - name: Install Ð¡ocoapods
      run: gem install cocoapods
    
    - name: Publish To CocoaPod Trunk Register
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        pod trunk push Bonjour.podspec --skip-import-validation --allow-warnings
